"""
Django settings for scratchr2 project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h019x@a&f0jvenw%@)p5o(r=bwt6b1kcbbw&142f5!rf9ba^#o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'scratchr2.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'scratchr2.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = (
    ('en',		'English '),
	('an',		'Aragonés'),
	('ast',		'Asturianu'),
	('id',		'Bahase Indonesia'),
	('ms',		'Bahasa Melayu'),
	('ca',		'Català'),
	('cs',		'Česky'),
	('cy',		'Cymraeg'),
	('da',		'Dansk'),
	('fa-af',	'Dari'),
	('de',		'Deutsch'),
	('et',		'Eesti'),
	('eo',		'Esperanto'),
	('es',		'Español'),
	('eu',		'Euskera'),
    ('fr',		'Français'),
	('fr-ca',	'Français (Canada)'),
	('ga',		'Gaeilge'),
	('gl',		'Galego'),
	('hr',		'Hrvatski'),
	('is',		'Íslenska'),
	('it',		'Italiano'),
	('rw',		'Kinyarwanda'),
	('ku',		'Kurdî'),
	('la',		'Latina'),
	('lv',		'Latviešu'),
	('lt',		'Lietuvių'),
	('hu',		'Magyar'),
	('mt',		'Malti'),
    ('cat',		'Meow'),
	('nl',		'Nederlands'),
	('nb',		'Norsk Bokmål'),
	('pl',		'Polski'),
	('pt',		'Português'),
	('pt-br',	'Português Brasileiro'),
	('ro',		'Română'),
	('sc',		'Sardu'),
	('sk',		'Slovenčina'),
	('sl',		'Slovenščina'),
	('fi',		'suomi'),
	('sv',		'Svenska'),
	('nai',		'Tepehuan'),
	('vi',		'Tiếng Việt'),
	('tr',		'Türkçe'),
	('ar',		'العربية'),
	('bg',		'Български'),
	('el',		'Ελληνικά'),
	('fa',		'فارسی'),
	('he',		'עִבְרִית'),
	('hi',		'हिन्दी'),
	('hy',		'Հայերեն'),
	('ja',		'日本語'),
	('ja-hr',	'にほんご'),
	('km',		'សំលៀកបំពាក'),
	('kn',		'ಭಾಷೆ-ಹೆಸರು'),
	('ko',		'한국어'),
	('mk',		'Македонски'),
	('ml',		'മലയാളം'),
	('mn',		'Монгол хэл'),
	('mr',		'मराठी'),
	('my',		'မြန်မာဘာသာ'),
	('ru',		'Русский'),
	('sr',		'Српски'),
	('th',		'ไทย'),
	('uk',		'Українська'),
	('zh-cn',	'简体中文'),
	('zh-tw',	'正體中文')
)

TIME_ZONE = 'EST'

USE_I18N = True

USE_TZ = True
LOCALE_PATHS = [BASE_DIR / 'locale']

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/scratchr2/static/'
STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_COOKIE_NAME='scratchcsrftoken'

CSRF_TRUSTED_ORIGINS = [
							"http://localhost",
							"http://publications-a.gl.at.ply.gg:15886",
							"http://127.0.0.1",
							"http://192.168.2.27"
							]
							
ALLOWED_HOSTS = [
							"localhost",
							"http://localhost",
							
							"http://publications-a.gl.at.ply.gg:15886",
							"http://publications-a.gl.at.ply.gg:15886",
							
							"127.0.0.1",
							"http://127.0.0.1",
							
							"192.168.2.27",
							"http://192.168.2.27"
							]