from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.utils import simplejson as json
from django.conf import settings

def error404(request, exception):
	return render(request, "404.html")
	
def error500(request, exception):
	return render(request, "500.html")
	
def homepage(request):
	context = {}
	# Test data based on https://scratch.mit.edu/site-api/projects/shared/
	# Studios test data taken from https://scratch.mit.edu/site-api/galleries/
	# Yes, I joined a random studio just for this
	
	# Test data uses the javascript-style true/false whereas we need the python-style True/False
	# When projects will be stored in the database, Django will automatically fix this for us
	false = False
	true = True
	context["featuredprojects"] = [
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 1", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 1},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 2", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 2}, 
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 3", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 3}, 
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 4", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 4},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 5", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 5},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 6", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 6},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 7", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 7},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 8", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 8},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 9", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 9},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 10", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 10},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 11", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 11},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 12", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 12},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 13", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 13},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 14", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 14},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 15", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 15},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 16", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 16},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 17", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 17},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 18", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 18},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 19", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 19},
									{"fields": {"view_count": 0, "favorite_count": 0, "remixers_count": 0, "creator": {"username": "test", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}, "title": "Project 20", "isPublished": true, "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/projects/thumbnails/default.png", "visibility": "visible", "love_count": 0, "datetime_modified": "2001-09-11T10:03:00", "uncached_thumbnail_url": "//cdn2.scratch.mit.edu/get_image/project/default_100x80.png", "thumbnail": "default.png", "datetime_shared": "2001-09-11T10:03:00", "commenters_count": 0}, "model": "projects.project", "pk": 20},
									]
	context["featuredgalleries"] = [
									{"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 1", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 1},
									{"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 2", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 2},
									{"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 3", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 3},
									{"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 4", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 4},
									{"fields": {"curators_count": 0, "projecters_count": 0, "title": "Gallery 5", "datetime_created": "2001-09-11T10:03:00", "thumbnail_url": "//uploads.scratch.mit.edu/get_image/gallery/default_170x100.png", "commenters_count": 0, "datetime_modified": "2001-09-11T10:03:00", "owner": {"username": "User", "pk": 1, "thumbnail_url": "//uploads.scratch.mit.edu/users/avatars/default.png", "admin": false}}, "model": "galleries.gallery", "pk": 5},
									]
	context["curated"] = context["featuredprojects"]
	context["sds"] = context["featuredprojects"]
	context["remixes"] = context["featuredprojects"]
	context["loves"] = context["featuredprojects"]
	return render(request, "homepage/index.html", context)

def forgot_settings_1(request):
	return render(request, "heather/forgot_settings_1.html")

def forgot_settings_2(request):
	return render(request, "heather/forgot_settings_2.html")

def csrf(request):
	"""
	On the OG HeatherscratchR 2, this function was a stub because
	modern django sets the CSRF cookie automatically.
	However, on Django 1.4, this isn't the case.
	As such, for ScratchR2_PY27, we have to get this working.
	Django seems to not want to give us the CSRF token that we need,
	so everything that uses a POST request is broken unless we disable csrf.
	"""
	response = HttpResponse()
	csrf_token = "placeholder"
	request.META["CSRF_COOKIE"] = csrf_token
	response.set_cookie(settings.CSRF_COOKIE_NAME,
						request.META["CSRF_COOKIE"],
						max_age = 60 * 60 * 24 * 7 * 52,
                        domain=settings.CSRF_COOKIE_DOMAIN,
                        path=settings.CSRF_COOKIE_PATH,
                        secure=settings.CSRF_COOKIE_SECURE
                        )

	return response

def session(request):
	response = HttpResponse(json.dumps({ }, indent=3))
	return response